# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 16
        uses: actions/setup-java@v2.3.0
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
          architecture: aarch64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Gradle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Gradle plugin
          path: icicle-gradle/build/libs/*.jar
      - name: Upload Core
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Icicle core
          path: icicle-core/build/libs/*.jar
      - name: Upload Serialization
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Icicle serialization
          path: icicle-serialization/build/libs/*.jar
      - name: Upload Utiltiies
        uses: actions/upload-artifact@v2.2.4
        with:
          name: Icicle utilities
          path: icicle-utilities/build/libs/*.jar
