# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 16 (Adopt)
        uses: actions/setup-java@v3.4.0
        with:
          java-version: '16' # I love you, Gradle!
          distribution: 'adopt'
          cache: gradle
          architecture: aarch64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Artifacts
          path: icicle-*/build/libs/*.jar
